=== espocrm/espocrm/schema/metadata/fields.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://www.espocrm.com/schema/metadata/fields.json",
    "title": "fields",
    "description": "Field definitions.",
    "type": "object",
    "properties": {
        "notMergeable": {
            "type": "boolean",
            "description": "Whether this field type is mergeable (when merging duplicate records)."
        },
        "notCreatable": {
            "type": "boolean",
            "description": "Whether the field of this type can be created in the Entity Manager tool."
        },
        "readOnly": {
            "type": "boolean",
            "description": "Is this field type Read Only (can't be edited)."
        },
        "skipOrmDefs": {
            "type": "boolean",
            "description": "Skip converting to defs for the ORM."
        },
        "filter": {
            "type": "boolean",
            "description": "Records can be filtered by this field (available as filter on the list view)."
        },
        "view": {
            "type": "string",
            "description": "A frontend view."
        },
        "params": {
            "type": "array",
            "description": "Field parameters.",
            "items": {
                "anyOf": [
                    {"const": "__APPEND__"},
                    {
                        "allOf": [
                            {
                                "$ref": "./entityDefs.json#/definitions/fieldDefs"
                            },
                            {
                                "properties": {
                                    "hidden": {
                                        "type": "boolean",
                                        "description": "Do not display the parameter in the field manager."
                                    },
                                    "name": {
                                        "type": "string",
                                        "description": "A name."
                                    }
                                }
                            }
                        ]
                    }
                ]
            }
        },
        "fieldDefs": {
            "description": "An object of field type definition",
            "$ref": "./entityDefs.json#/definitions/fieldDefs"
        },
        "translatedOptions": {
            "type": "boolean",
            "description": "Does the field have options that can be translated."
        },
        "hookClassName": {
            "type": "string",
            "description": "A hook class. Called after the field is created or edited in the Entity Manager tool."
        },
        "fields": {
            "type": "object",
            "description": "Definitions of additional fields that will be created with this field. E.g. for address field, separate fields (street, city, etc.) are created.",
            "additionalProperties": {
                "$ref": "./entityDefs.json#/definitions/fieldDefs"
            }
        },
        "naming": {
            "enum": ["suffix", "prefix"],
            "description": "The naming determines how additional fields will be named."
        },
        "actualFields": {
            "type": "array",
            "items": {
                "type": "string"
            },
            "description": "The list of actual attributes (which contain useful data). For example, for field type link in actualFields is ['id'], in notActualFields is ['name']. Means, if you load record with link field, you have values in {fieldName}Id and {fieldName}Name (suffix naming). But you need set only {fieldName}Id, if you want to update this field."
        },
        "notActualFields": {
            "type": "array",
            "items": {
                "type": "string"
            },
            "description": "The list of not actual attributes."
        },
        "personalData": {
            "type": "boolean",
            "description": "Where the field may contain personal data."
        },
        "textFilter": {
            "type": "boolean",
            "description": "The field will be available in the list of text filters (in the Entity Manager tool)."
        },
        "textFilterForeign": {
            "type": "boolean",
            "description": "The field will be available in the list of text filters as a foreign field."
        },
        "linkDefs": {
            "$ref": "./entityDefs.json#/definitions/linkDefs",
            "description": "If defined, a link with the same name as the field name will be created."
        },
        "fullTextSearch": {
            "type": "boolean",
            "description": "Full-text search will be available for the field."
        },
        "fullTextSearchColumnList": {
            "type": "array",
            "items": {
                "type": "string"
            },
            "description": "Columns used in full-text search."
        },
        "default": {
            "description": "Currently is not used. A default value. Used when populating defaults for a new record. Usually to be set to null."
        },
        "valueFactoryClassName": {
            "type": "string",
            "description": "A factory that creates value-objects for this field. A value-object can be obtained by calling getValueObject method on an Entity. Should implement Espo\\ORM\\Value\\ValueFactory."
        },
        "attributeExtractorClassName": {
            "type": "string",
            "description": "A class that extracts values (attribute => value map) from a value-object. Used internally for obtaining values from a value-object and writing them to an entity. Should implement Espo\\ORM\\Value\\AttributeExtractor."
        },
        "validationList": {
            "type": "array",
            "items": {
                "anyOf": [
                    {"type": "string"},
                    {"const": "__APPEND__"}
                ]
            },
            "description": "Validations applied server-side."
        },
        "mandatoryValidationList": {
            "type": "array",
            "items": {
                "anyOf": [
                    {"type": "string"},
                    {"const": "__APPEND__"}
                ]
            },
            "description": "Validations applied server-side."
        },
        "validatorClassNameMap": {
            "type": "object",
            "description": "Validators. Should implement Espo\\Core\\FieldValidation\\Validator.",
            "additionalProperties": {
                "type": "string",
                "description": "A validation name."
            }
        },
        "duplicatorClassName": {
            "type": "string",
            "description": "Duplicates attributes of a field. Some fields can require some processing when an entity is being duplicated. Should implement Espo\\Core\\Record\\Duplicator\\FieldDuplicator."
        },
        "converterClassName": {
            "type": "string",
            "description": "A metadata converter. Converts field metadata to ORM metadata. Should implement Espo\\Core\\Utils\\Database\\Orm\\FieldConverter."
        },
        "sanitizerClassName": {
            "type": "string",
            "description": "A sanitizer. Should implement Espo\\Core\\FieldSanitize\\Sanitizer."
        },
        "sanitizerClassNameList": {
            "type": "array",
            "items": {"type": "string"},
            "description": "Sanitizers. Classes should implement Espo\\Core\\FieldSanitize\\Sanitizer. As of v8.2."
        },
        "massUpdateActionList": {
            "type": "array",
            "items": {"type": "string"},
            "description": "Actions for mass update."
        }
    }
}

=== espocrm/espocrm/application/Espo/Resources/metadata/fields/url.json
{
    "params": [
        {
            "name": "required",
            "type": "bool",
            "default": false
        },
        {
            "name": "default",
            "type": "varchar"
        },
        {
            "name": "maxLength",
            "type": "int"
        },
        {
            "name": "strip",
            "type": "bool",
            "tooltip": "urlStrip"
        },
        {
            "name": "protocolRequired",
            "type": "bool"
        },
        {
            "name": "copyToClipboard",
            "type": "bool",
            "default": false
        },
        {
            "name": "audited",
            "type": "bool"
        },
        {
            "name": "readOnly",
            "type": "bool"
        },
        {
            "name": "readOnlyAfterCreate",
            "type": "bool"
        }
    ],
    "validationList": [
        "required",
        "maxLength",
        "valid"
    ],
    "mandatoryValidationList": [
        "maxLength",
        "valid"
    ],
    "filter": true,
    "fieldDefs": {
        "type": "varchar"
    },
    "sanitizerClassNameList": [
        "Espo\\Classes\\FieldSanitizers\\StringTrim"
    ],
    "personalData": true,
    "default": null
}

=== espocrm/espocrm/application/Espo/Resources/metadata/fields/file.json
{
    "params": [
        {
            "name": "required",
            "type": "bool",
            "default": false
        },
        {
            "name": "sourceList",
            "type": "multiEnum",
            "view": "views/admin/field-manager/fields/source-list"
        },
        {
            "name": "maxFileSize",
            "type": "float",
            "tooltip": true,
            "min": 0
        },
        {
            "name": "accept",
            "type": "multiEnum",
            "noEmptyString": true,
            "allowCustomOptions": true,
            "options": [
                "image/*",
                "audio/*",
                "video/*",
                ".zip",
                ".pdf",
                ".odt",
                ".ods",
                ".odp",
                ".docx",
                ".xlsx",
                ".pptx",
                ".doc",
                ".xls",
                ".ppt",
                ".rtf",
                ".csv",
                ".md",
                ".txt"
            ],
            "tooltip": "fileAccept"
        },
        {
            "name": "readOnly",
            "type": "bool"
        },
        {
            "name": "readOnlyAfterCreate",
            "type": "bool"
        },
        {
            "name": "audited",
            "type": "bool"
        }
    ],
    "actualFields": [
        "id"
    ],
    "notActualFields": [
        "name"
    ],
    "converterClassName": "Espo\\Core\\Utils\\Database\\Orm\\FieldConverters\\File",
    "validationList": [
        "required",
        "pattern"
    ],
    "mandatoryValidationList": [
        "pattern"
    ],
    "filter": true,
    "linkDefs": {
        "type": "belongsTo",
        "entity": "Attachment",
        "skipOrmDefs": true,
        "utility": true
    },
    "personalData": true,
    "duplicatorClassName": "Espo\\Classes\\FieldDuplicators\\File"
}

=== espocrm/espocrm/application/Espo/Resources/metadata/fields/datetimeOptional.json
{
   "params":[
      {
         "name": "required",
         "type": "bool",
         "default": false
      },
      {
         "name":"default",
         "type":"enum",
         "view": "views/admin/field-manager/fields/date/default",
         "options": [
            "",
            "javascript: return this.dateTime.getNow(1);",
            "javascript: return this.dateTime.getNow(5);",
            "javascript: return this.dateTime.getNow(15);",
            "javascript: return this.dateTime.getNow(30);",
            "javascript: return this.dateTime.getDateTimeShiftedFromNow(1, 'hours', 15);",
            "javascript: return this.dateTime.getDateTimeShiftedFromNow(2, 'hours', 15);",
            "javascript: return this.dateTime.getDateTimeShiftedFromNow(3, 'hours', 15);",
            "javascript: return this.dateTime.getDateTimeShiftedFromNow(4, 'hours', 15);",
            "javascript: return this.dateTime.getDateTimeShiftedFromNow(5, 'hours', 15);",
            "javascript: return this.dateTime.getDateTimeShiftedFromNow(6, 'hours', 15);",
            "javascript: return this.dateTime.getDateTimeShiftedFromNow(7, 'hours', 15);",
            "javascript: return this.dateTime.getDateTimeShiftedFromNow(8, 'hours', 15);",
            "javascript: return this.dateTime.getDateTimeShiftedFromNow(9, 'hours', 15);",
            "javascript: return this.dateTime.getDateTimeShiftedFromNow(10, 'hours', 15);",
            "javascript: return this.dateTime.getDateTimeShiftedFromNow(11, 'hours', 15);",
            "javascript: return this.dateTime.getDateTimeShiftedFromNow(12, 'hours', 15);",
            "javascript: return this.dateTime.getDateTimeShiftedFromNow(1, 'days', 15);",
            "javascript: return this.dateTime.getDateTimeShiftedFromNow(2, 'days', 15);",
            "javascript: return this.dateTime.getDateTimeShiftedFromNow(3, 'days', 15);",
            "javascript: return this.dateTime.getDateTimeShiftedFromNow(4, 'days', 15);",
            "javascript: return this.dateTime.getDateTimeShiftedFromNow(5, 'days', 15);",
            "javascript: return this.dateTime.getDateTimeShiftedFromNow(6, 'days', 15);",
            "javascript: return this.dateTime.getDateTimeShiftedFromNow(1, 'week', 15);"
         ],
         "translation": "FieldManager.options.dateTimeDefault"
      },
      {
         "name":"after",
         "type":"varchar"
      },
      {
         "name":"before",
         "type":"varchar"
      },
      {
         "type": "bool",
         "name":"useNumericFormat"
      },
      {
         "name":"audited",
         "type":"bool"
      },
      {
         "name":"readOnly",
         "type":"bool"
      }
   ],
   "actualFields":[
      "",
      "date"
   ],
   "fields":{
      "date": {
         "type": "date",
         "disabled": true
      }
   },
   "filter": true,
   "notCreatable": true,
   "fieldDefs":{
      "type":"datetime",
      "notNull":false
   },
   "view": "views/fields/datetime-optional",
   "personalData": true
}

=== espocrm/espocrm/application/Espo/Resources/metadata/fields/linkParent.json
{
    "params"         : [
        {
            "name"   : "required",
            "type"   : "bool",
            "default": false
        }
    ],
    "actualFields"   : [
        "id",
        "type"
    ],
    "notActualFields": [
        "name"
    ],
    "filter"         : true,
    "notCreatable"   : true,
    "fieldDefs"      : {
        "notStorable": true
    }
}

=== espocrm/espocrm/application/Espo/Resources/metadata/fields/enumFloat.json
{
   "params":[
      {
         "name":"options",
         "type":"array"
      },
      {
         "name":"default",
         "type":"float"
      },
      {
         "name":"audited",
         "type":"bool"
      },
      {
         "name":"readOnly",
         "type":"bool"
      }
   ],
   "filter": true,
   "notCreatable": true,
   "fieldDefs":{
      "type":"float"
   }
}

=== espocrm/espocrm/application/Espo/Resources/metadata/fields/phone.json
{
    "params": [
        {
            "name": "required",
            "type": "bool",
            "default": false
        },
        {
            "name": "typeList",
            "type": "array",
            "default": [
                "Mobile",
                "Office",
                "Home",
                "Fax",
                "Other"
            ],
            "view": "views/admin/field-manager/fields/options"
        },
        {
            "name": "defaultType",
            "type": "enum",
            "default": "Mobile",
            "view": "views/admin/field-manager/fields/phone/default"
        },
        {
            "name": "audited",
            "type": "bool"
        }
    ],
    "actualFields": [
        "isOptedOut",
        "isInvalid",
        "",
        "data"
    ],
    "notActualFields": [],
    "fields": {
        "isOptedOut": {
            "type": "bool",
            "notStorable": true,
            "layoutDetailDisabled": true,
            "layoutDefaultSidePanelDisabled": true,
            "mergeDisabled": true,
            "customizationDefaultDisabled": true,
            "customizationReadOnlyDisabled": true,
            "customizationInlineEditDisabledDisabled": true
        },
        "isInvalid": {
            "type": "bool",
            "notStorable": true,
            "layoutDetailDisabled": true,
            "layoutDefaultSidePanelDisabled": true,
            "mergeDisabled": true,
            "customizationDefaultDisabled": true,
            "customizationReadOnlyDisabled": true,
            "customizationInlineEditDisabledDisabled": true
        }
    },
    "converterClassName": "Espo\\Core\\Utils\\Database\\Orm\\FieldConverters\\Phone",
    "validationList": [
        "required",
        "valid",
        "maxLength"
    ],
    "mandatoryValidationList": [
        "valid",
        "maxLength"
    ],
    "notCreatable": true,
    "filter": true,
    "fieldDefs": {
        "notStorable": true
    },
    "translatedOptions": true,
    "textFilter": true,
    "personalData": true,
    "valueFactoryClassName": "Espo\\Core\\Field\\PhoneNumber\\PhoneNumberGroupFactory",
    "attributeExtractorClassName": "Espo\\Core\\Field\\PhoneNumber\\PhoneNumberGroupAttributeExtractor",
    "sanitizerClassName": "Espo\\Classes\\FieldSanitizers\\Phone",
    "default": null
}
